description: >
  Invoke the Makefile build target

parameters:
  cgo_enabled:
    description: The value of the CGO_ENABLED environment variable to use
    type: string
    default: "0"
  run_generate:
    description: Whether to run `go generate` prior to `go build`
    type: boolean
    default: true
  run_get:
    description: Whether to run `go get` prior to `go build`
    type: boolean
    default: true

steps:
  - cache-modules
  - run:
      name: Build Go executables
      environment:
        CGO_ENABLED: << parameters.cgo_enabled >>
        GO111MODULE: "on"
        GOARCH: "amd64"
        GOOS: "linux"
        GOPRIVATE: "github.com/AchievementNetwork/*"
        GORUNGENERATE: <<# parameters.run_generate >>yes<</ parameters.run_generate>>
        GORUNGET: <<# parameters.run_get >>yes<</ parameters.run_get>>
      command: |
        make build
