description: >
  Invoke the Makefile build target

parameters:
  cgo_enabled:
    description: The value of the CGO_ENABLED environment variable to use
    type: string
    default: "0"

steps:
  - cache-modules
  - run:
      name: Build Go executables
      environment:
        CGO_ENABLED: << parameters.cgo_enabled >>
        GO111MODULE: "on"
        GOARCH: "amd64"
        GOOS: "linux"
        GOPRIVATE: "github.com/AchievementNetwork/*"
      command: |
        make build
