description: >
  Build go executables

executor:
  name: default
  version: <<parameters.go_version>>

parameters:
  cgo_enabled:
    description: The value of the CGO_ENABLED environment variable
    type: string
    default: "0"
  go_version:
    description: The version of GoLang to use
    type: string
    default: '1.15'

steps:
  - build:
      cgo_enabled: << parameters.cgo_enabled >>
