description: >
  Default executor for Go projects

docker:
  - image: 'circleci/golang:<<parameters.version>>'

parameters:
  version:
    description: >
      The version of GoLang to use
    type: string
    default: '1.15'
